/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Shahrukh
 */
public class Board extends javax.swing.JFrame {

    /**
     * Creates new form Board
     */
    private byte turn;
    public Board() {
        initComponents();
        turn = 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        oNe = new javax.swing.JLabel();
        thRee = new javax.swing.JLabel();
        foUr = new javax.swing.JLabel();
        tWo = new javax.swing.JLabel();
        sIx = new javax.swing.JLabel();
        seVen = new javax.swing.JLabel();
        eiGht = new javax.swing.JLabel();
        niNe = new javax.swing.JLabel();
        fiVe = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 1, true));

        oNe.setBackground(java.awt.Color.lightGray);
        oNe.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        oNe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oNe.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        oNe.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
			public void mouseClicked(java.awt.event.MouseEvent evt) {
                oNeMouseClicked(evt);
            }
            @Override
			public void mouseEntered(java.awt.event.MouseEvent evt) {
                oNeMouseEntered(evt);
            }
            @Override
			public void mouseExited(java.awt.event.MouseEvent evt) {
                oNeMouseExited(evt);
            }
        });

        thRee.setBackground(java.awt.Color.lightGray);
        thRee.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        thRee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thRee.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        thRee.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
			public void mouseClicked(java.awt.event.MouseEvent evt) {
                thReeMouseClicked(evt);
            }
            @Override
			public void mouseEntered(java.awt.event.MouseEvent evt) {
                thReeMouseEntered(evt);
            }
            @Override
			public void mouseExited(java.awt.event.MouseEvent evt) {
                thReeMouseExited(evt);
            }
        });

        foUr.setBackground(java.awt.Color.lightGray);
        foUr.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        foUr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foUr.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        foUr.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
			public void mouseClicked(java.awt.event.MouseEvent evt) {
                foUrMouseClicked(evt);
            }
            @Override
			public void mouseEntered(java.awt.event.MouseEvent evt) {
                foUrMouseEntered(evt);
            }
            @Override
			public void mouseExited(java.awt.event.MouseEvent evt) {
                foUrMouseExited(evt);
            }
        });

        tWo.setBackground(java.awt.Color.lightGray);
        tWo.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        tWo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tWo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tWo.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
			public void mouseClicked(java.awt.event.MouseEvent evt) {
                tWoMouseClicked(evt);
            }
            @Override
			public void mouseEntered(java.awt.event.MouseEvent evt) {
                tWoMouseEntered(evt);
            }
            @Override
			public void mouseExited(java.awt.event.MouseEvent evt) {
                tWoMouseExited(evt);
            }
        });

        sIx.setBackground(java.awt.Color.lightGray);
        sIx.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        sIx.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sIx.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        sIx.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
			public void mouseClicked(java.awt.event.MouseEvent evt) {
                sIxMouseClicked(evt);
            }
            @Override
			public void mouseEntered(java.awt.event.MouseEvent evt) {
                sIxMouseEntered(evt);
            }
            @Override
			public void mouseExited(java.awt.event.MouseEvent evt) {
                sIxMouseExited(evt);
            }
        });

        seVen.setBackground(java.awt.Color.lightGray);
        seVen.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        seVen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seVen.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        seVen.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
			public void mouseClicked(java.awt.event.MouseEvent evt) {
                seVenMouseClicked(evt);
            }
            @Override
			public void mouseEntered(java.awt.event.MouseEvent evt) {
                seVenMouseEntered(evt);
            }
            @Override
			public void mouseExited(java.awt.event.MouseEvent evt) {
                seVenMouseExited(evt);
            }
        });

        eiGht.setBackground(java.awt.Color.lightGray);
        eiGht.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        eiGht.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eiGht.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        eiGht.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
			public void mouseClicked(java.awt.event.MouseEvent evt) {
                eiGhtMouseClicked(evt);
            }
            @Override
			public void mouseEntered(java.awt.event.MouseEvent evt) {
                eiGhtMouseEntered(evt);
            }
            @Override
			public void mouseExited(java.awt.event.MouseEvent evt) {
                eiGhtMouseExited(evt);
            }
        });

        niNe.setBackground(java.awt.Color.lightGray);
        niNe.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        niNe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        niNe.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        niNe.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
			public void mouseClicked(java.awt.event.MouseEvent evt) {
                niNeMouseClicked(evt);
            }
            @Override
			public void mouseEntered(java.awt.event.MouseEvent evt) {
                niNeMouseEntered(evt);
            }
            @Override
			public void mouseExited(java.awt.event.MouseEvent evt) {
                niNeMouseExited(evt);
            }
        });

        fiVe.setBackground(java.awt.Color.lightGray);
        fiVe.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        fiVe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fiVe.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fiVe.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
			public void mouseClicked(java.awt.event.MouseEvent evt) {
                fiVeMouseClicked(evt);
            }
            @Override
			public void mouseEntered(java.awt.event.MouseEvent evt) {
                fiVeMouseEntered(evt);
            }
            @Override
			public void mouseExited(java.awt.event.MouseEvent evt) {
                fiVeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(seVen, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oNe, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foUr, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fiVe, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sIx, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tWo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(thRee, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(eiGht, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(niNe, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oNe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thRee, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tWo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sIx, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(niNe, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(foUr, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seVen, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fiVe, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eiGht, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tic Tac Toe");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oNeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oNeMouseEntered
        // TODO add your handling code here:
        oNe.setBackground(Color.GRAY);
    }//GEN-LAST:event_oNeMouseEntered

    private void oNeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oNeMouseExited
        // TODO add your handling code here:
       oNe.setBackground(Color.lightGray);
    }//GEN-LAST:event_oNeMouseExited

    private void tWoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tWoMouseEntered
        // TODO add your handling code here:
        tWo.setBackground(Color.GRAY);
    }//GEN-LAST:event_tWoMouseEntered

    private void tWoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tWoMouseExited
        // TODO add your handling code here:
        tWo.setBackground(Color.lightGray);
    }//GEN-LAST:event_tWoMouseExited

    private void thReeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thReeMouseEntered
        // TODO add your handling code here:
        thRee.setBackground(Color.GRAY);
    }//GEN-LAST:event_thReeMouseEntered

    private void thReeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thReeMouseExited
        // TODO add your handling code here:
        thRee.setBackground(Color.lightGray);
    }//GEN-LAST:event_thReeMouseExited

    private void foUrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foUrMouseEntered
        // TODO add your handling code here:
        foUr.setBackground(Color.GRAY);
    }//GEN-LAST:event_foUrMouseEntered

    private void foUrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foUrMouseExited
        // TODO add your handling code here:
        foUr.setBackground(Color.lightGray);
    }//GEN-LAST:event_foUrMouseExited

    private void fiVeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiVeMouseEntered
        // TODO add your handling code here:
        fiVe.setBackground(Color.GRAY);
    }//GEN-LAST:event_fiVeMouseEntered

    private void fiVeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiVeMouseExited
        // TODO add your handling code here:
        fiVe.setBackground(Color.lightGray);
    }//GEN-LAST:event_fiVeMouseExited

    private void sIxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sIxMouseEntered
        // TODO add your handling code here:
        sIx.setBackground(Color.GRAY);
    }//GEN-LAST:event_sIxMouseEntered

    private void sIxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sIxMouseExited
        // TODO add your handling code here:
        sIx.setBackground(Color.lightGray);
    }//GEN-LAST:event_sIxMouseExited

    private void seVenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seVenMouseEntered
        // TODO add your handling code here:
        seVen.setBackground(Color.GRAY);
    }//GEN-LAST:event_seVenMouseEntered

    private void seVenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seVenMouseExited
        // TODO add your handling code here:
        seVen.setBackground(Color.lightGray);
    }//GEN-LAST:event_seVenMouseExited

    private void eiGhtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eiGhtMouseEntered
        // TODO add your handling code here:
        eiGht.setBackground(Color.GRAY);
    }//GEN-LAST:event_eiGhtMouseEntered

    private void eiGhtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eiGhtMouseExited
        // TODO add your handling code here:
        eiGht.setBackground(Color.lightGray);
    }//GEN-LAST:event_eiGhtMouseExited

    private void niNeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_niNeMouseEntered
        // TODO add your handling code here:
        niNe.setBackground(Color.GRAY);
    }//GEN-LAST:event_niNeMouseEntered

    private void niNeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_niNeMouseExited
        // TODO add your handling code here:
        niNe.setBackground(Color.lightGray);
    }//GEN-LAST:event_niNeMouseExited

    private void oNeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oNeMouseClicked
        // TODO add your handling code here:
        setPlayerPosition(oNe);
    }//GEN-LAST:event_oNeMouseClicked

    private void tWoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tWoMouseClicked
        // TODO add your handling code here:
        setPlayerPosition(tWo);
    }//GEN-LAST:event_tWoMouseClicked

    private void thReeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thReeMouseClicked
        // TODO add your handling code here:
        setPlayerPosition(thRee);
    }//GEN-LAST:event_thReeMouseClicked

    private void foUrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foUrMouseClicked
        // TODO add your handling code here:
        setPlayerPosition(foUr);

    }//GEN-LAST:event_foUrMouseClicked

    private void fiVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiVeMouseClicked
        // TODO add your handling code here:
        setPlayerPosition(fiVe);
    }//GEN-LAST:event_fiVeMouseClicked

    private void sIxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sIxMouseClicked
        // TODO add your handling code here:
        setPlayerPosition(sIx);
    }//GEN-LAST:event_sIxMouseClicked

    private void seVenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seVenMouseClicked
        // TODO add your handling code here:
        setPlayerPosition(seVen);
    }//GEN-LAST:event_seVenMouseClicked

    private void eiGhtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eiGhtMouseClicked
        // TODO add your handling code here:
        setPlayerPosition(eiGht);
    }//GEN-LAST:event_eiGhtMouseClicked

    private void niNeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_niNeMouseClicked
        // TODO add your handling code here:
        setPlayerPosition(niNe);
    }//GEN-LAST:event_niNeMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eiGht;
    private javax.swing.JLabel fiVe;
    private javax.swing.JLabel foUr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel niNe;
    private javax.swing.JLabel oNe;
    private javax.swing.JLabel sIx;
    private javax.swing.JLabel seVen;
    private javax.swing.JLabel tWo;
    private javax.swing.JLabel thRee;
    // End of variables declaration//GEN-END:variables

    
    
    private void setPlayerPosition(JLabel label){
        if(label.getText().isEmpty() || label.getText().equals("")){
            if(turn == 1){
                label.setText("O");
                turn = 2;
                whoIsTheWinner();
            }else{
                label.setText("X");
                turn = 1;
                whoIsTheWinner();
            }
        }else{
            label.setText(label.getText());
        }
    }
    
    
    private void whoIsTheWinner(){
        if(oNe.getText().equals("O") && fiVe.getText().equals("O") && niNe.getText().equals("O") ||
                thRee.getText().equals("O") && fiVe.getText().equals("O") && seVen.getText().equals("O") ||
                oNe.getText().equals("O") && tWo.getText().equals("O") && thRee.getText().equals("O") ||
                foUr.getText().equals("O") && fiVe.getText().equals("O") && sIx.getText().equals("O") ||
                seVen.getText().equals("O") && eiGht.getText().equals("O") && niNe.getText().equals("O") ||
                oNe.getText().equals("O") && foUr.getText().equals("O") && seVen.getText().equals("O") ||
                tWo.getText().equals("O") && fiVe.getText().equals("O") && eiGht.getText().equals("O") ||
                thRee.getText().equals("O") && sIx.getText().equals("O") && niNe.getText().equals("O"))
        {
            JOptionPane.showMessageDialog(new JFrame(), "O's player won the match!");
            oNe.setText("");    tWo.setText("");    thRee.setText("");    foUr.setText("");     fiVe.setText("");
            sIx.setText("");    seVen.setText("");  eiGht.setText("");      niNe.setText("");
            turn = 1;
        }
        else if(oNe.getText().equals("X") && fiVe.getText().equals("X") && niNe.getText().equals("X") ||
                thRee.getText().equals("X") && fiVe.getText().equals("X") && seVen.getText().equals("X") ||
                oNe.getText().equals("X") && tWo.getText().equals("X") && thRee.getText().equals("X") ||
                foUr.getText().equals("X") && fiVe.getText().equals("X") && sIx.getText().equals("X") ||
                seVen.getText().equals("X") && eiGht.getText().equals("X") && niNe.getText().equals("X") ||
                oNe.getText().equals("X") && foUr.getText().equals("X") && seVen.getText().equals("X") ||
                tWo.getText().equals("X") && fiVe.getText().equals("X") && eiGht.getText().equals("X") ||
                thRee.getText().equals("X") && sIx.getText().equals("X") && niNe.getText().equals("X"))
        {
            JOptionPane.showMessageDialog(new JFrame(), "X's player won the match!");
            oNe.setText("");    tWo.setText("");    thRee.setText("");    foUr.setText("");     fiVe.setText("");
            sIx.setText("");    seVen.setText("");  eiGht.setText("");      niNe.setText("");
            turn = 1;

        }
        else if(!oNe.getText().isEmpty() && !tWo.getText().isEmpty() && !thRee.getText().isEmpty() && !foUr.getText().isEmpty() &&
                !fiVe.getText().isEmpty() && !sIx.getText().isEmpty() && !seVen.getText().isEmpty() && !eiGht.getText().isEmpty() &&
                !niNe.getText().isEmpty() ){
            JOptionPane.showMessageDialog(new JFrame(), "It's a tie!");
            oNe.setText("");    tWo.setText("");    thRee.setText("");    foUr.setText("");     fiVe.setText("");
            sIx.setText("");    seVen.setText("");  eiGht.setText("");      niNe.setText("");
            turn = 1;
        }
    }
    
    
    
    
    
    
    public JLabel getEiGht() {
        return eiGht;
    }

    public void setEiGht(JLabel eiGht) {
        this.eiGht = eiGht;
    }

    public JLabel getFiVe() {
        return fiVe;
    }

    public void setFiVe(JLabel fiVe) {
        this.fiVe = fiVe;
    }

    public JLabel getFoUr() {
        return foUr;
    }

    public void setFoUr(JLabel foUr) {
        this.foUr = foUr;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JLabel getNiNe() {
        return niNe;
    }

    public void setNiNe(JLabel niNe) {
        this.niNe = niNe;
    }

    public JLabel getoNe() {
        return oNe;
    }

    public void setoNe(JLabel oNe) {
        this.oNe = oNe;
    }

    public JLabel getsIx() {
        return sIx;
    }

    public void setsIx(JLabel sIx) {
        this.sIx = sIx;
    }

    public JLabel getSeVen() {
        return seVen;
    }

    public void setSeVen(JLabel seVen) {
        this.seVen = seVen;
    }

    public JLabel gettWo() {
        return tWo;
    }

    public void settWo(JLabel tWo) {
        this.tWo = tWo;
    }

    public JLabel getThRee() {
        return thRee;
    }

    public void setThRee(JLabel thRee) {
        this.thRee = thRee;
    }
}
